### ISSUE TITLE
within doesn't work with this

### ISSUE THREAD

**Issue by Jalle19** [komazarari/capistrano-locally#13]
It seems all `within` blocks are simply skipped, i.e. the code inside them doesn't run.

**Comment by Jalle19** [comment]
@komazarari any idea on how to fix this?

**Comment by Jalle19** [comment]
e.g. I have a task like this:

```
namespace :ops do
    desc "Clone ops repository"
    task :clone do
      on roles(:all) do
        within "/home/ubuntu" do
          if test("[ ! -d ops ]")
            execute :"ssh-keyscan", "bitbucket.org > ~/.ssh/known_hosts"
            execute :git, "clone ", fetch(:ops_repo_url)
          end
        end
      end
    end
end
```

Which is run using this:

```
before :starting, "ops:clone"
```

But the whole task is simply skipped. It can't be the `roles(:all)` because I use that in other tasks and they execute just fine.

**Comment by komazarari** [comment]
Hi, sorry for late reply and thank you for describing the details.
But I couldn't reproduce this problem, I think this is related to `before` hook with namespace.

Could you try simply single task by `cap <stage> ops:clone  --trace` and check it works or not?
If your problem is caused by `within` block, the single task will not work correctly. Otherwise, it's better to check the `before` hook, for example, try changing `before :starting ...` to `before "deploy:starting"`, etc.

**Comment by Jalle19** [comment]
I'll try and report back, thanks for the tips!

**Comment by Jalle19** [comment]
@komazarari this is what I get when running the task explicitly:

```
$ cap localhost ops:clone --trace
** Invoke localhost (first_time)
** Execute localhost
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke ops:clone (first_time)
** Execute ops:clone
```

**Comment by Jalle19** [comment]
It seems to only fail when using `within "/hardcoded/path"`. If I use e.g. `within release_path` it works fine.

**Comment by Jalle19** [comment]
"Fixed" it by changing the whole task to:

```
desc "Clone ops repository"
task :clone do
  on roles(:all) do
	  if !File.directory?(fetch(:ops_path))
		execute :"ssh-keyscan", "bitbucket.org > ~/.ssh/known_hosts"
		execute :git, "clone ", fetch(:ops_repo_url), fetch(:ops_path)
	  end
  end
end
```

Now since it doesn't use `within` it "just works"

**Comment by Jalle19** [comment]
Just noticed that `within` works perfectly in another repository that uses the exact same code. Losing my mind with this.
